# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PackageDeliveryApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FirebaseMessaging'

  # Pods for PackageDeliveryApp

  target 'PackageDeliveryApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PackageDeliveryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PackageDeliveryApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  


  # Pods for PackageDeliveryApp-tvOS


end
